---
name: CHI-Driver-DBI
version: 1.0
author:
  - 'Perrin Harkins <perrin@elem.com>'
abstract: Use DBI for cache storage
license: perl
requires:
  CHI: 0.102
  DBI: 0
build_requires:
  CHI: 0
  Test::Class: 0
  Test::More: 0
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  CHI::Driver::DBI:
    file: lib/CHI/Driver/DBI.pm
    version: 1.0
  CHI::t::Driver::DBI:
    file: lib/CHI/t/Driver/DBI.pm
  CHI::t::Driver::DBI::SQLite:
    file: lib/CHI/t/Driver/DBI/SQLite.pm
  CHI::t::Driver::DBI::mysql:
    file: lib/CHI/t/Driver/DBI/mysql.pm
resources:
  license: http://dev.perl.org/licenses/
