---
abstract: 'Use DBI for cache storage'
author:
  - 'Jonathan Swartz <swartz@pobox.com>'
build_requires:
  Test::Class: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200000, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CHI-Driver-DBI
no_index:
  directory:
    - lib/CHI/Driver/DBI/t
    - lib/CHI/Driver/DBI/Test
  file:
    - lib/CHI/Driver/DBI/Util.pm
requires:
  CHI: 0.241
  DBI: 1.26
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=CHI-Driver-DBI
  repository: git://github.com/jonswar/perl-chi-driver-dbi.git
version: 1.25
